Use auto-generated input files

diff --git a/images/worker/Dockerfile b/images/worker/Dockerfile
--- a/images/worker/Dockerfile
+++ b/images/worker/Dockerfile
@@ -47,16 +47,25 @@ RUN if [ ${INCLUDE_SIMULINK} = true ]; then \
     fi
 
 # Run mpm to install MATLAB toolboxes.
-ENV TOOLBOX_FILE=${INPUT_DIR}/toolboxes.txt
+ENV MATLAB_TOOLBOX_FILE=${INPUT_DIR}/matlab-toolboxes.txt
 RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
     && chmod +x mpm \
     && sudo HOME=${USER_HOME} ./mpm install \
-    --inputfile ${TOOLBOX_FILE} \
+    --inputfile ${MATLAB_TOOLBOX_FILE} \
     || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
-    && sudo rm -rf mpm /tmp/mathworks_root.log ${TOOLBOX_FILE}
+    && sudo rm -rf mpm /tmp/mathworks_root.log ${MATLAB_TOOLBOX_FILE}
+
+# Run mpm to install Simulink toolboxes.
+ENV SIMULINK_TOOLBOX_FILE=${INPUT_DIR}/simulink-toolboxes.txt
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
+    && chmod +x mpm \
+    && sudo HOME=${USER_HOME} ./mpm install \
+    --inputfile ${SIMULINK_TOOLBOX_FILE} \
+    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
+    && sudo rm -rf mpm /tmp/mathworks_root.log ${SIMULINK_TOOLBOX_FILE}
 
 # Run mpm to install support packages into the matlab user's HOME folder.
-ENV SUPPORT_PACKAGE_FILE=${INPUT_DIR}/support_packages.txt
+ENV SUPPORT_PACKAGE_FILE=${INPUT_DIR}/support-packages.txt
 RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
     && chmod +x mpm \
     && sudo HOME=${USER_HOME} ./mpm install \
